FROM node:18.16-alpine as builder

WORKDIR /app

COPY ./package-lock.json ./
COPY ./package.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:1.24.0-alpine

COPY --from=builder ./app/dist /usr/share/nginx/html