FROM node:18.16-alpine AS builder

WORKDIR /app/frontend
COPY ./package-lock.json ./
COPY ./package.json ./
RUN npm install
COPY . .
RUN npm run build 

FROM nginx:1.24-alpine 
COPY --from=builder ./app/build /usr/share/nginx/html
EXPOSE 80